return PlaceObj('ModDef', {
	'title', "Rato Dev",
	'dependencies', {},
	'id', "WxLXvdc",
	'author', "rato",
	'version', 384,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"Code/ForceDev.lua",
		"Code/magazine_check.lua",
		"Code/magazine_build.lua",
		"Code/extract_functions.lua",
		"Code/fix_editor_enemysquads.lua",
		"Code/PrintAttack.lua",
		"Code/FirearmExec_debug.lua",
		"Code/CheckIfChangedPatchingMethod.lua",
		"Code/used_comps_brute_TOG.lua",
		"Code/Script1.lua",
	},
	'default_options', {},
	'saved', 1733625252,
	'code_hash', 3147335035452218159,
	'affected_resources', {},
})