return PlaceObj('ModDef', {
	'title', "Rato Dev",
	'dependencies', {},
	'id', "WxLXvdc",
	'author', "rato",
	'version', 336,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"Code/ForceDev.lua",
		"Code/CheckIfChangedPatchingMethod.lua",
		"Code/extract_functions.lua",
		"Code/Script.lua",
		"Code/magazine_check.lua",
		"Code/magazine_build.lua",
		"Code/PrintAttack.lua",
		"Code/FirearmExec_debug.lua",
		"Code/fix_editor_enemysquads.lua",
		"Code/Script1.lua",
	},
	'default_options', {},
	'saved', 1733177678,
	'code_hash', 6730613354227390709,
	'affected_resources', {},
})